languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "HG021B的博客"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/avatar.png"
  description = "绅士帽和探索兔的结合就像\"Rabbit Hole\"，这是我们在未知攻防世界中探索的象征。"

[params.author]
  name = "HG021B"
  email = "hg021b@htomail.com"
  image = "img/avatar2.png"
  headline = "绅士帽和探索兔的结合就像\"Rabbit Hole\"，这是我们在未知攻防世界中探索的象征。"
  bio = "绅士帽和探索兔的结合就像\"Rabbit Hole\"，这是我们在未知攻防世界中探索的象征。"
  links = [
    { x-twitter = "https://twitter.com/" },
    { github = "https://github.com/hg021b" },
  ]